accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as loginViews


urlpatterns=[
	url(r'^login/$',
		loginViews.login,
		name="login"),
	url(r'^logout/$',
		loginViews.logout,
		name="logout"),
]

clinica/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from optica import urls as optUrls
from main import urls as mainUrls
from accounts import urls as accUrls



urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^cuentas/',
        include(accUrls)),

    url(r'^',
    	include(mainUrls,namespace="main")),

    url(r'^optica/',
    	include(optUrls,namespace="optica")),

    url(
        regex=r'^media/(?P<path>.*)$',
        view='django.views.static.serve',
        kwargs={'document_root':settings.MEDIA_ROOT}
        ),

]

main/urls.py
from django.conf.urls import url
from . import views



urlpatterns=[
	url(r'^$',
		views.Home.as_view(),
		name="home"),
]

optica/urls.py
from django.conf.urls import url
from . import views



urlpatterns=[

	url(r'^$',
		views.SelectPaciente.as_view(),
		name="paciente"),

	url(r'^(?P<paciente_id>\d+)/$',
		views.Ncita.as_view(),
		name="nueva_cita"),


]

accounts/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

optica/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse


class Paciente(models.Model):
	CHOICES=(
		('opcion1','Opcion1'),
		('opcion2','Opcion2'),
		)
	SEX_CHOICES=(
		('mujer','Mujer'),
		('hombre','Hombre'),
		('otro','Otro')
		)
	estado=models.CharField(max_length=20, choices=CHOICES, default='opcion2')
	nombre=models.CharField(max_length=100)
	edad=models.IntegerField()
	sexo=models.CharField(max_length=10,choices=SEX_CHOICES,default='Mujer')
	direccion=models.TextField()
	fecha_nacimiento=models.DateField(blank=True,null=True)
	edad=models.TextField(max_length=5,blank=True,null=True)
	foto=models.ImageField(upload_to='users/%Y/%m/%d',blank=True)

	def __str__(self):
		return self.nombre

	def get_absolute_url_optica(self):
		return reverse('optica:nueva_cita',args=[self.id])

class OptExp(models.Model):
	paciente=models.OneToOneField(Paciente)
	enfermedad=models.CharField(max_length=200)
	dato2=models.CharField(max_length=100,blank=True,null=True)
	dato3=models.CharField(max_length=100,blank=True,null=True)
	
	def __str__(self):
		return "Expediente optica de {}".format(self.paciente)

class Chequeo(models.Model):
	CHOICES=(
		('opcion1','Opcion1'),
		('opcion2','Opcion2'),
		)
	TUBOS=(
		('tuboGrande','TuboGrande'),
		('TuboChico','tubochico'),
		)
	expediente=models.ForeignKey(OptExp,related_name='chequeos')
	fecha=models.DateTimeField(auto_now=True)
	graduacion=models.CharField(max_length=100,choices=TUBOS,default='TuboChico')
	observaciones=models.TextField()
	compra=models.BooleanField(default=True)
	armazon=models.CharField(max_length=50,choices=CHOICES,default='opcion1')

	def __str__(self):
		return "Consultas del {} de {}".format(self.fecha,self.expediente)

ventas/models.py
from django.db import models
from django.conf import settings 
from django.core.urlresolvers import reverse


#Me falta generar algo aquí que nos permita grabar el costo del lente y hacer las evidentes 
#operaciones matemáticas sobre los costos e importes, abonos y todo lo que incluye pagos :S

class Pagos(model.Models):
	STATUS_PAGOS_CHOICES=(
		('pagado','Pagado'),
		('abono','Abonado'),
		('liquidado','Liquidado'),
		('pp','Pago Parcial'),
		('pl','Pago Parcial liquida contraentrega')
		)
	statusPagos=models.CharField(max_length=100, choices=STATUS_PAGOS_CHOICES,default='pagado')
    pagoParcialLiquidaContraentrega=models.CharField(max_length=50,blank=True,null=True,)

	def __str__(self):
		return self.statusPagos

class Descuentos(model.Models):
	DESCUENTOS_INSTITUCIONALES_CHOICES=(
		('10%','Institución1 10%'),
		('20%','Institución2 20%'),
		('30%','Institución3 30%'),
		('40%','Institución4 40%'),
		('50%','Institución5 50%'),
		)
	descuentosInstitucionales=models.CharField(max_length=50, choices=DESCUENTOS_INSTITUCIONALES_CHOICES, default='10%')
	
	def __str__(self):
		return self.descuentosInstitucionales

class Entregas(models.Models):
	STATUS_ENTREGAS_LENTES_CHOICES=(
		('entregado','Entregado a Cliente'),
		('pedido','Pedido a proveedor'),
		('laboratorio','En elaboración'),
		)
	statusEntregas=models.CharField(max_length=100, choices=STATUS_ENTREGAS_LENTES_CHOICES,default='pedido')
	
	def __str__(self):
		return self.statusEntregas

optica/forms.py
from django import forms
from .models import Paciente, Chequeo


class SelecPacienteForm(forms.Form):
	paciente = forms.ModelChoiceField(queryset=Paciente.objects.all(), 
                                  label="Paciente")

class PacienteForm(forms.ModelForm):
	class Meta:
		model=Paciente
		fields=['nombre','edad','sexo','direccion','fecha_nacimiento','foto','estado']

class ChequeoForm(forms.ModelForm):
	class Meta:
		model=Chequeo
		fields=['graduacion','observaciones','compra','armazon']

main/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class Home(TemplateView):
	template_name="main/home.html"

optica/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.core.urlresolvers import reverse
from django.views.generic import View
# Herramienta para restringir acceso
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
# formularios paciente
from .forms import SelecPacienteForm, PacienteForm, ChequeoForm
# modelos
from .models import Paciente


class SelectPaciente(View):
	@method_decorator(login_required(login_url='login'))
	def get(self,request):
		template="optica/nueva_cita.html"
		pacienteform=SelecPacienteForm()
		pacientes=Paciente.objects.all()
		context={
		'pacientes':pacientes,
		'pform':pacienteform,
		
		}
		return render(request,template,context)

	def post(self,request):
		# pacienteform=SelecPacienteForm(request.POST)
		paciente_id=request.POST.get('paciente')
		print(paciente_id)
		return redirect('optica:nueva_cita',paciente_id=paciente_id)

class Ncita(View):
	@method_decorator(login_required(login_url='login'))
	def get(self,request,paciente_id):
		paciente=get_object_or_404(Paciente,pk=paciente_id)
		chequeos=paciente.optexp.chequeos.all().order_by('-fecha')
		cform=ChequeoForm()
		template="optica/detalle.html"
		context={
		'paciente':paciente,
		'chequeos':chequeos,
		'cform':cform,
		}
		return render(request,template,context)

	def post(self,request,paciente_id):
		paciente=get_object_or_404(Paciente,pk=paciente_id)
		new_cform=ChequeoForm(request.POST)
		if new_cform.is_valid():
			new_chequeo=new_cform.save(commit=False)
			new_chequeo.expediente=paciente.optexp
			new_chequeo.save()
		return redirect('optica:nueva_cita',paciente_id=paciente.id)

ventas/views.py
from django.shortcuts import render

# Create your views here.

main/templates/main/home.html
{%extends 'base.html'%}
{%load static%}

{%block titulo%}Bienvenido{%endblock titulo%}

{%block content%}


  <div class="slider">
    <ul class="slides">
      <li>
        <img src="http://vahq.net/images/healthcare.jpg"> <!-- random image -->
        <div class="caption center-align fondito">
          <h3>Sistema Integral de Servicio Medico</h3>
          <h5 class="light grey-text text-lighten-3">Development by: Montserrat Cristina Morato </h5>
        </div>
      </li>
      <li>
        <img src="http://olympusdialysis.com/wp-content/uploads/2014/05/doctors.jpg"> <!-- random image -->
        <div class="caption center-align fondito">
          <h3>Sistema Integral de Servicio Medico</h3>
          <h5 class="light grey-text text-lighten-3">Development by: Montserrat Cristina Morato </h5>
        </div>
      </li>
  </ul>
</div>



{%endblock content%}

{%block scripts%}
<script>
 $(document).ready(function(){
      $('.slider').slider({full_width: true,
      					indicators:false,
      					height:700});
    });

</script>
{%endblock scripts%}

optica/templates/optica/detalle.html
{%extends 'base.html'%}
{%load static%}

{%block titulo%}Optica - Cita{%endblock titulo%}

{%block content%}
<section class="section">
<section class="container">
  <article class="row">
    <div class="datos col m3 white">
      <img class="responsive-img" src="{{paciente.foto.url}}">
      <h5>DATOS DEL PACIENTE</h5>
        <p><strong>Nombre:</strong>
          {{paciente.nombre}}</p>
        <p><strong>Edad:</strong>
          {{paciente.edad}}</p>
        <p><strong>Sexo:</strong>
          {{paciente.sexo}}</p>
        <p><strong>Direccón:</strong>
          {{paciente.direccion}}</p>
        <p><strong>Fecha de Nacimiento:</strong>
          {{paciente.fecha_nacimiento}}</p>


    </div>

    <div class="expediente col m9 grey lighten-3">
      <h4>HISTORIAL MEDICO DEL PACIENTE</h4>
      <p>Enfermedad: {{paciente.optexp.enfermedad}}</p>
      <p>dato2: {{paciente.optexp.dato2}}</p>
      <p>dato3: {{paciente.optexp.dato3}}</p>

      <div class="chequeos">

        <ul class="collection">
        {%for chequeo in chequeos%}
        <div class="collection-item">
        <li>fecha de consulta: {{chequeo.fecha}}</li>
        <li>graduacion: {{chequeo.graduacion}}</li>
        <li>observaciones: {{chequeo.observaciones}}</li>
        <li>
          {%if chequeo.compra%}Armazon: {{chequeo.armazon}}{%endif%}
        </li>
        </div>

        {%empty%}
        <li><strong>No hay consultas anteriores</strong></li>
        {%endfor%}

        </ul>

      </div>


    </div>






  </article>










 <div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
    <a class="waves-effect btn-floating btn-large blue modal-trigger" href="#modal1">
      <i class="large material-icons">add</i>
    </a>
  </div>


  </section>
  </section>


    <!-- Modal Structure -->
  <div id="modal1" class="modal">
    <div class="modal-content">
      <h4>Agregar Chequeo</h4>
      <p>
      	<form action="{%url 'optica:nueva_cita' paciente.id%}" method="post">
      		{%csrf_token%}
      		{{cform.as_table}}
      		<input type="hidden" name="selector" value="chequeo">
      		<input type="submit" value="Agregar" class="btn blue">
      	</form>
      </p>
    </div>
    <div class="modal-footer">
      <a href="#!" class=" modal-action modal-close waves-effect waves-green btn red">Cancelar</a>
    </div>
  </div>


{%endblock content%}

{%block scripts%}
<script>
$(document).ready(function(){
    // the "href" attribute of .modal-trigger must specify the modal ID that wants to be triggered
    $('.modal-trigger').leanModal();
    $('select').material_select();
  });

</script>
{%endblock scripts%}

optica/templates/optica/nueva_cita.html
{%extends 'base.html'%}
{%load static%}

{%block titulo%}Optica - Cita{%endblock titulo%}

{%block content%}
<section class="container">

<div class="buscador row">
		<h5 class="col s12">Seleccione el Paciente</h5>

		<form action="." method="post">
		{%csrf_token%}
		{{pform.as_p}}
		<input type="hidden" name="selector" value="paciente">
		<input type="submit" value="seleccionar" class="btn blue">
	</form>


	<input class="col s10" type="text"><i class="material-icons col s2">Buscar</i>


</div>

  <ul class="collection">
    {%for paciente in pacientes%}
    <a href="{{paciente.get_absolute_url_optica}}">
    <li class="collection-item avatar">
      <img src="{{paciente.foto.url}}" alt="" class="circle">
      <span class="title">Nombre: {{paciente.nombre}}</span>
      <p>Edad: {{paciente.edad}} <br>
         Sexo: {{paciente.sexo}}
      </p>
      <i class="secondary-content material-icons">info_outline</i>
    </li>
    </a>
    {%empty%}
   <li class="collection-item">
    NO HAY PACIENTES PARA MOSTRAR
   </li>
   {%endfor%}
    </ul>




  </section>


{%endblock content%}

{%block scripts%}
<script>
$(document).ready(function(){
    // the "href" attribute of .modal-trigger must specify the modal ID that wants to be triggered
    $('.modal-trigger').leanModal();
    $('select').material_select();
  });

</script>
{%endblock scripts%}

templates/base.html
{%load static%}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width:device-width">
	<title>{%block titulo%}Clinica{%endblock titulo%}</title>
	 <!--Import Google Icon Font-->
      <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">

     
	  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">


	<link rel="stylesheet" type="text/css" href="{%static 'css/bliss.css'%}">
</head>
<body>
	<nav class="blue">
    <div class="nav-wrapper">
      <a href="{%url 'main:home'%}" class="brand-logo">Clínica - Chonita</a>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <li><a href="#!">Urgencias</a></li>
        <li><a href="#!">Maternidad</a></li>
        <li><a href="{%url 'optica:paciente'%}">
<i class="fa fa-eye" aria-hidden="true"></i>
          Optica</a></li>
        <li><a href="#!">Medicina aeroespacial </a></li>
        <li class="blue darken-2">
        	{%if request.user.is_authenticated%}
        	<strong>
        	Hola {{request.user.first_name}}
        </strong>
        	</li>
        	<li class="blue darken-2">
        		<a href="{%url 'logout'%}">
        			Cerrar Sesión
        		</a>
        	
        	{%else%}
        	<a href="{%url 'login'%}">Acceso al sistema </a>
        	{%endif%}
        </li>
      </ul>
      <ul class="side-nav" id="mobile-demo">
        <li><a href="#!">Urgencias</a></li>
        <li><a href="#!">Maternidad</a></li>
        <li><a href="{%url 'optica:paciente'%}">
<i class="fa fa-eye" aria-hidden="true"></i>
Optica</a></li>
        <li><a href="#!">Medicina aeroespacial </a></li>
        <li>
        	{%if request.user.is_authenticated%}
        	<strong>
        	Hola {{request.user.first_name}}
        </strong>

        	</li>
        	<li>
        		<a href="{%url 'logout'%}">
        			Cerrar Sesión
        		</a>
        	
        	{%else%}
        	<a href="{%url 'login'%}">Acceso al sistema </a>
        	{%endif%}
        </li>
      </ul>
    </div>
  </nav>
	{%block content%}

	{%endblock content%}





<!--Import jQuery before materialize.js-->
      <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
      
  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>

<script>
$( document ).ready(function() {
    $(".button-collapse").sideNav();
});
</script>
    
{%block scripts%}
{%endblock scripts%}
</body>
</html>